-- ## FILE FORMAT ## --
CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  SKIP_HEADER = 1
  error_on_column_count_mismatch=false;

SHOW FILE FORMATS; 
DESC FILE FORMAT CSV_FORMAT; 