CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.US_ACCIDENTS_DATA_STAGE_S3
    URL = '' -- bucket URL s3://my_bucket_name
    -- bellow options isnt necessary, are just options 
     -- FILE_FORMAT = ( CSV | JSON | AVRO | ORC | PARQUET | XML ) -- IF DEFAULT FILE_FORMATS ATTENDS YOUR NEEDS
     -- CREDENTIALS = ( AWS_KEY_ID = ''AWS_SECRET_KEY = '') -- IF YOU DONT WANT TO USE STORAGE INTEGRATION, YOU CAN USE CREDENTIALS
     -- ENCRYPTION = ( TYPE = 'AWS_CSE', MASTER_KEY = '')
     -- COPY OPTIONS = ()
     -- TAG = '' -- TO TRACK COSTS 
    STORAGE_INTEGRATION = S3_INTEGRATION; 

LIST @MANAGE_DB.EXTERNAL_STAGES.US_ACCIDENTS_DATA_STAGE_S3;

DESC STAGE US_ACCIDENTS_DATA_STAGE_S3;

SHOW STAGES; 