USE DATABASE MANAGE_DB; 

CREATE OR REPLACE SCHEMA MANAGE_DB.PIPES; 

-- CREATE SNOWPIPE TO AUTOMATIZE YOUR INGESTION 
CREATE OR REPLACE PIPE MANAGE_DB.PIPES.ACCIDENTS_USA_RAW
    AUTO_INGEST = TRUE
    COMMENT = 'Pipe to autoingest us accidents data from s3'
 AS 
 COPY INTO ACCIDENTS.USA.RAW
  FROM @MANAGE_DB.EXTERNAL_STAGES.US_ACCIDENTS_DATA_STAGE_S3
  FILE_FORMAT = MANAGE_DB.FILE_FORMATS.CSV_FORMAT
  ON_ERROR = CONTINUE -- CONTINUE || SKIP_FILE || OTHERS -- IT'S USED FOR INGESTION ERROR HANDLING PURPOSES
;

DESC PIPE ACCIDENTS_USA_RAW;

SELECT * FROM ACCIDENTS.USA.RAW;

SELECT SYSTEM$PIPE_STATUS('ACCIDENTS_USA_RAW'); -- SNOWPIPE STATUS

-- is used to resume the execution of a pipeline.
ALTER PIPE MANAGE_DB.PIPES.ACCIDENTS_USA_RAW SET PIPE_EXECUTION_PAUSED = false;

--  the action of triggering a Snowpipe process to ingest and load new data from an external stage into a target table in Snowflake.
ALTER PIPE MANAGE_DB.PIPES.ACCIDENTS_USA_RAW REFRESH; 

-- VALIDATE LOAD 
SELECT * FROM TABLE(validate_pipe_load(
PIPE_NAME => 'MANAGE_DB.PIPES.ACCIDENTS_USA_RAW',
START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
));

-- ALL INFORMATION ABOUT COPY 
SELECT *
  FROM TABLE (INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'ACCIDENTS.USA.RAW',
  START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
  ));

-- USAGE_HISTORIC OF YOUR SNOWPIPE
SELECT * 
  FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
  DATE_RANGE_START=> DATEADD(DAYS,-2,CURRENT_TIMESTAMP()),
  PIPE_NAME => 'MANAGE_DB.PIPES.ACCIDENTS_USA_RAW'
  ));

  SELECT * FROM ACCIDENTS.USA.RAW LIMIT 1000;

